### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#10]
I finished gui subsystem, try using. A big request to look and say your opinion. Now added only base classes, such button, widget, label, signal/slot impl, event.

**Comment by gecube** [comment]
It is working ! :+1:

**Comment by captnfab** [comment]
I can't build it. I first had to change the encoding of screen_wait.cpp to utf8 (it was written in utf16 and refused by gcc). Then I fixed the makefile to take into account the changes. But finally, gcc gives me an error since you use itoa which is a non-standard C function.

**Comment by dalerank** [comment]
ok... gecube fixed it near

**Comment by gecube** [comment]
Please, take a look into branch "dalerank" in my repository - I've fixed compatibility issues.

**Comment by captnfab** [comment]
Ok, thx gecube.

**Comment by captnfab** [comment]
I compiled the new version, thank you to both of you :)

I have some comments. I'm not sure which ones are "work in progress" and which ones are bugs :) 
1) I see the game doesn't crash anymore when we remove houses / etc. \o/
2) A right clic doesn't close the menu anymore (eg. click on the "industries" menu, and then try to close it)
3) Choosing the "houses" tool doesn't close an opened menu
4) The perspective is not respected anymore when a new building is built
5) Population and money are not updated
6) The large menu is not available.
7) Scrolling with the arrows is not fluid

I hope this helps!

**Comment by dalerank** [comment]
in morning i merged with gecube changes and fixed lot of bugs, if you want try updated rev.

**Comment by captnfab** [comment]
This was from the last rev in gecube dalerank branch (https://github.com/gecube/opencaesar3/commit/ec4faf5c7698ad4606a92f07bccb2f0952a49ec1). I'm not sure when "morning" is from your point of view :)
I'm trying your last rev (1e0376b) :)

**Comment by captnfab** [comment]
I got some errors:
screen_game.o: In function `ScreenGame::initialize(GfxEngine&, GuiEnv&)':
opencaesar3/screen_game.cpp:62: undefined reference to`InfoBoxManager::create(GuiEnv_)'
screen_game.o: In function `ScreenGame::showTileInfo(Tile_)':
/home/fgivors/projets/opencaesar3/screen_game.cpp:165: undefined reference to `InfoBoxManager::showHelp(Tile*)'

If you are IRC users, we could create a room to discuss in realtime about all that :)

**Comment by dalerank** [comment]
may be skype???

**Comment by captnfab** [comment]
Maybe, the day it becomes open-source with a 64bits console client... :)

**Comment by dalerank** [comment]
good joke)))

**Comment by dalerank** [comment]
skype: "my_nickname"_pda

**Comment by dalerank** [comment]
i think need append this *.o(infoboxmanager.o) in linker section... sorry i haven't now linux on my note

**Comment by captnfab** [comment]
Oh, I see, wait, I'll provide you with a patch for that.

**Comment by captnfab** [comment]
Err... I don't know how to add a "dalerank" branch based on your "master" to my repo... (Sorry, first time using github, and not a git-maniac...) How should I do that?

**Comment by dalerank** [comment]
hmmm... you simple will may create brach from my master... it git, it simple

**Comment by captnfab** [comment]
That's precisely the thing I don't know how to do :)

**Comment by dalerank** [comment]
ok... just minute

git checkout origin/dalerank/master
git checkout -b newBranch

may be gecube will help, if i have mistake

**Comment by captnfab** [comment]
Looks like I did it, with a pull --rebase : https://github.com/captnfab/opencaesar3/commit/58d51e46a1ae95efe57f607eb3e42e49865503f4

Ill try your version next time ;)

**Comment by gathanase** [comment]
The scrolling with arrows was never really fluid, the tilemap is moved each
time a tile (or half a tile) up/down/right/left.

**Comment by dalerank** [comment]
yes, i known... it my mistake now... later i will fix it

**Comment by dalerank** [comment]
Some fix for gui are added( click&drag, scrolling, rmb click now work more correct and yet small other), pls test for bugs. Thanks all.

**Comment by captnfab** [comment]
Hi Dalerank,

I got a 
gui_tilemap.cpp:29:32: fatal error: oc3_roadpropagator.h: No such file or directory

did you forget to add this file? :)

**Comment by dalerank** [comment]
Sorry, sometimes I happen scattered

**Comment by captnfab** [comment]
Thanks, it very nice, good job! :)
I noticed some issues :
- After building a rectangle of houses, if I select one temple (for example), there is some glitch at the begining
- When using the "remove" tool, all the sprites used are those of the building under the pointer
- And it crashes when I use the remove tool to remove multiple buildings

**Comment by gecube** [comment]
- After building a rectangle of houses, if I select one temple (for example), there is some glitch at the begining
- When using the "remove" tool, all the sprites used are those of the building under the pointer
- And it crashes when I use the remove tool to remove multiple buildings

I agreed...

**Comment by dalerank** [comment]
thanks... some time need to fix those bugs (((
