### ISSUE TITLE
Automated resources extractor.

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#100]
Is it need a small app( such sgreader or part of sgreader), which will assume creation of opencaesar3 resource files from files by original game? ? ?

**Comment by Rovanion** [comment]
Yes. Right now resources.7z contains files not available on the original Caesar 3 CD. Are these additional resources listed anywhere? Does anyone know exactly the files are and how to get them?

**Comment by dalerank** [comment]
i create link for pics_oc3.zip in wiki...  https://github.com/gecube/opencaesar3/wiki/opencaesar3-own-resources
or you can download direct [pics_oc3.zip](https://www.dropbox.com/s/f3fa0v1gexy5lhv/pics_oc3.zip)

**Comment by gecube** [comment]
Now we can invoke sgreader for extracting resources from original game. We can write script for generating resources for opencaesar, using sgreader, or one may upgrade sgreater tool to do all necessary steps.

**Comment by dalerank** [comment]
I think less peoples will pass so many steps to install and try project, unfortunately many want have app "in one button".

anybody want resolve this task (app-extractor) ???

i think it may be part of opencaesar execute file, which check resources dir and extract/renamed/pack files from original game

**Comment by Rovanion** [comment]
Yes it would be handy if on first launch of openCaesar3, if the resources aren't present in the resources folder, the game presents the user with a dialogue:

-___________________________________________________ - + x
openCaesar III requires resources from the original Caesar III to run. 
Please specify the path to a Caesar III CD or ISO.

[Browse...]   |/path/entered/by/user                                               |

[Exit game]   [Next ->]
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

From there a script deals with the whole extraction process from CD to finished resource folder during which a progress bar is displayed. After the resource folder is populated the user can start the game.

**Comment by gecube** [comment]
OK. I'd thought and found this idea damn good. The only thing to mention is that dialogue must be displayed in case if any resource file required by program is absent instead of displaying error message and exiting.

I'll take this part of work and will finish it to the end of week. Also I want to ask - what do you think about dependencies on Qt? Or what library we will use for dialog box?

**Comment by dalerank** [comment]
We also have qt-dependecies in project, caesar app when not found some resources may start sgreader with some params, forexample "sgreader -rc" (say sgreader that need create resouce)

**Comment by dalerank** [comment]
moved to https://github.com/gecube/opencaesar3/issues/124
