### ISSUE TITLE
[Need implement] Desirability overlay

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#114]
![27](https://f.cloud.github.com/assets/918081/599555/02e9e7fa-cc53-11e2-8397-d4be18d6b30e.png)

**Comment by gecube** [comment]
This is desirability ("желательность") or in another words - value of the land.

**Comment by Rovanion** [comment]
Is it possible for you as maintainer to rename the report or does the
reporter have to do it?

2013/6/4 George Gaál notifications@github.com

**Comment by dalerank** [comment]
![oc3_ 0221 05 _10_0910](https://f.cloud.github.com/assets/918081/630084/75ffba24-d18c-11e2-8264-4c4570c61c60.png)
![oc3_ 0221 05 _10_0911](https://f.cloud.github.com/assets/918081/630085/7616e226-d18c-11e2-81b9-faf6ad03472d.png)
