### ISSUE TITLE
[Need implement] Garden's creating + infobox

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#118]
![23](https://f.cloud.github.com/assets/918081/599570/58da2cec-cc53-11e2-93fa-a7b5f2ae6d0d.png)

**Comment by ghost** [comment]
I've started working on this, along with statues. Currently, I can build them, and use their info boxes but only one type of garden can be built and they won't group together. 

Quick screenshot:
![image](https://f.cloud.github.com/assets/4605795/606938/204367c4-cd37-11e2-8fbb-c28e6f9612bb.png)

**Comment by ghost** [comment]
Just a few notes on how gardens seem to operate in original Caesar 3, based of my testing. Corrections welcome.

Garden tile type seems to be fixed, that is by knowing the x,y coord of the map you can tell what type of garden will show up there. This works from the top corner of the map in squares of 4 tiles, with 110 at the top, then going round counter clockwise to 113. The placement icon is always 110.

The way garden tiles merge together seems to also be fixed, but varies from map to map. You can see this yourself by clearing out a map and covering the whole thing in garden. Adding or removing random squares of garden can make the related row/col of gardens adjust, however you can always end up back at the same pattern by filling them back in. Also, there appears the be 3 different types of matched garden squares, a squareish one and two roundish ones.

Gameplay wise, garden is walkable with no penalty (currently in OC3 there seems to be the same movement penalty as being off road). Garden can not be destroyed by fire or collapse. One would assume disasters are capable of destroying garden but I haven't tested this. Requires no road access or water (requires road in OC3 at the moment). The current model data for gardens in OC3 seems to match the original.

**Comment by Rovanion** [comment]
Just adding a short question: The reason why gardens don't catch fire in
the original game is because they don't require a road and therefore aren't
ever visited by a prefect, right?

2013/6/5 Tracer Tong notifications@github.com

**Comment by dalerank** [comment]
Yes, in original game gardens can't start fire, but can destroyed by disaster. I'll try fix it near time.

**Comment by ghost** [comment]
@dalerank: thanks for the movement speed on gardens fix!
@Rovanion: I'm not sure what the reason behind it in the original is, I can't seem to select walkers on garden either, maybe they hide in bush. It would make sense that gardens could burn too, maybe they could be configured to catch fire if a neighbouring building is on fire, but not be able to start fire themselves (avoid the prefect/road issue). This differs from the original though.

I've just removed the road requirement of gardens, and sorted out the different types of single square gardens as they were in original C3. Merging gardens together into the larger multi square gardens still remains to do though.

**Comment by Rovanion** [comment]
@tracertong It makes sense to have them run the risk of catching fire if neighbouring buildings are on fire. And personally I think it's a fine change to make.

**Comment by dalerank** [comment]
yes... you can create issue for it, but now i think we need restore functions like in original game with such precision as possible, and later we can do own changes and improvements to gameplay. i think if now do some changes wayout original, it may we do other game before finished. Also if you want to do some serious improvements you always can do it in new branch.

**Comment by ghost** [comment]
@dalerank Totally agree :)

So gardens should be functioning normally now, except for the purely visual aspect of them grouping together in to 2x2 gardens, so I'll leave this open.

On a side note, I'm also preparing a commit that will fix the issues (that I'm aware of) with statues.

**Comment by ghost** [comment]
Another note while I remember, the images for the 2x2 gardens are:
114 - roundish with fancier middle bit
115 - roundish
116 - squareish

**Comment by dalerank** [comment]
![oc3_ 2013_06_02_15_25_12](https://f.cloud.github.com/assets/918081/736118/7fdfcb30-e30a-11e2-9b20-d94179c76b67.png)
![oc3_ 2013_06_02_15_25_17](https://f.cloud.github.com/assets/918081/736119/84869164-e30a-11e2-94b5-a2249bb184df.png)
![oc3_ 2013_06_02_15_25_24](https://f.cloud.github.com/assets/918081/736121/893ea458-e30a-11e2-864f-1053737f42a2.png)
![oc3_ 2013_06_02_15_25_31](https://f.cloud.github.com/assets/918081/736122/8daf97fe-e30a-11e2-9442-04dce6b0736f.png)
![oc3_ 2013_06_02_15_25_53](https://f.cloud.github.com/assets/918081/736124/919e94fa-e30a-11e2-9e3e-ded166df2b93.png)
![oc3_ 2013_06_02_15_25_58](https://f.cloud.github.com/assets/918081/736125/963bbda8-e30a-11e2-9ff4-573bf68a142a.png)
![oc3_ 2013_06_02_15_26_04](https://f.cloud.github.com/assets/918081/736127/9a28463e-e30a-11e2-8abf-24c4cc6fa92d.png)
![oc3_ 2013_06_02_15_26_13](https://f.cloud.github.com/assets/918081/736128/9decfc60-e30a-11e2-8265-d8ebc0944ae8.png)
