### ISSUE TITLE
[2gathanase]New previewTiles API does not fit well for click&drag

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#12]
1. It was my probe of engine. 
2. As you can see postTiles it is repetition of your code, only I changed a drawing order, having put drawing of possible construction after drawing of all card, it gave the chance of correct imposing.
3. I took original game for an example, you can compare images to the original.
4. Perhaps my changes will help you to improve drawing, try to combine it with your ideas

**Comment by gecube** [comment]
Yes! We need to try different approaches, different ideas. What is good will survive, what is bad will be gone.
