### ISSUE TITLE
Own folder for translations.

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#122]
What you think about move translation(libintl) files to folder ./locale???
forexample ./locale/en/LC_MESSAGES/caesar.mo for english
                 ./locale/ru/LC_MESSAGES/caesar.mo for russian e.t.c

**Comment by gecube** [comment]
I like this idea.

**Comment by ghost** [comment]
Good idea!

Some extra thoughts, it would be awesome if we could include steps in the build process to generate the locale directories and caesar.mo files from available *.po files, unfortunately I know nothing about cmake though. Also where would the source files fit into this structure? Can we put them in a subdirectory of ./locale? Is it better to leave them in a separate directory in the root dir?

**Comment by gecube** [comment]
@tracertong 

> if we could include steps in the build process to generate the locale directories and caesar.mo files from available *.po files

good.

> unfortunately I know nothing about cmake though.

cmake isn't very complex. It has bash-like syntax. Of course, you can learn how to work with cmake with adding of small changes to our files and checking what they will do. Also I want to point you that @hellium write cmake-files.

> Also where would the source files fit into this structure?

Will fit. As I understand, *.po files are generated from source code files with the help of xgettext tool. So *.po file must be generated again after every change of source code files. *.mo files are compiled *.po for use in executable.

> Can we put them in a subdirectory of ./locale?

Yes.

> Is it better to leave them in a separate directory in the root dir?

Maybe
