### ISSUE TITLE
Move source code files to different catalogues.

### ISSUE THREAD

**Issue by gecube** [gecube/opencaesar3#123]
The our project becomes bigger and complex. So now we have over 300 files in main directory. It is big number. And directory in future will look like garbage dump. It's not good. So I suggest to divide project in small groups of files by their purpose. For example, such components can be distinguished:
- GUI elements (widgets, buttons, boxes);
- GUI (particular use of elements in game, dialogs);
- description of different buildings;
- description of different walkers (actors);
- game engine (save/load map, inner loop of game, game mechanics);
- some general things like work with PNG, compression support (PKware), smart pointers etc.

I want to discuss with you do you like such division? Do you have other ideas on this issue?

**Comment by ghost** [comment]
Yes! I've only known about this project for 4 days and I'm already sick of scrolling down that directory!

**Comment by Rovanion** [comment]
Is it also possible to drop the oc3_ prefixes for all source file or do they serve some purpose?

**Comment by gecube** [comment]
@Rovanion Why do you want to drop oc3_ prefix? It makes sense for me because oc3 files are part of only opencaesar3 project. Other files such sgreager sources, pkware, png for sdl don't have such prefix.

**Comment by dalerank** [comment]
@tracertong project have a lot of structures, which need for work, i think that original game have such files more greatly then us, imho

Forexample, i use logical folders in text editor
![workspace](https://f.cloud.github.com/assets/918081/617136/64178efa-ce89-11e2-9800-71bae461fac6.png)

**Comment by Rovanion** [comment]
@gecube It could just be that I haven't understood the purpose of the oc3_ prefix. About every file in the root of the project right now are prefixed oc3_ except for installation and license instructions. SGReader files are in the sgreader folder so there's no need to have a prefix there to differentiate between the two project files, the folders do that. SDL is installed by the system package manager and so on.
