### ISSUE TITLE
[BUG] Advisors window exit button have no pressed state image 

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#125]
Employer button (have pressed state image)
![paneling_00255](https://f.cloud.github.com/assets/918081/616519/7831091a-ce71-11e2-8a4c-452027d8e4b2.png)
![paneling_00268](https://f.cloud.github.com/assets/918081/616523/7fe3d962-ce71-11e2-9234-b99ece8b9db9.png)

Exit button (only normal state button)
![paneling_00267](https://f.cloud.github.com/assets/918081/616516/5fccbd88-ce71-11e2-9f1f-cb6a8477c8d7.png)

**Comment by ghost** [comment]
I had an attempt at this, here's the result, though the shading may be a bit much. Free to use if you like:
![image](https://f.cloud.github.com/assets/4605795/617092/253cbd50-ce88-11e2-91be-71420302b6f0.png)
![image](https://f.cloud.github.com/assets/4605795/617091/222cc51a-ce88-11e2-830b-5b2a2ed10b9e.png)

**Comment by dalerank** [comment]
thanks... i put this into pics_oc3.zip near commit
