### ISSUE TITLE
[Test] low bridge

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#139]
![oc3_ 2013_05_14_18_32_54](https://f.cloud.github.com/assets/918081/654611/a59192aa-d4ff-11e2-8b45-e7d4e88f6d47.png)
![oc3_ 2013_05_14_18_33_15](https://f.cloud.github.com/assets/918081/654612/a5b1c5f2-d4ff-11e2-97d6-0b8103dc8163.png)
![oc3_ 2013_05_14_18_33_11](https://f.cloud.github.com/assets/918081/654613/a5c923e6-d4ff-11e2-8475-20e951b5b42f.png)

**Comment by dalerank** [comment]
Any ideas how fix last screen situation???

**Comment by gecube** [comment]
Yes. We need to fix offsets of pictures when drawing the walkers over the bridge.

**Comment by dalerank** [comment]
Fixed. need testing.
