### ISSUE TITLE
How culture level is calculated?

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#142]

**Comment by gecube** [comment]
Please read [this article](http://www.citybuildingcontests.net/Caesar-Alan/The%20Appian%20Way%20-%20Culture%20Rating.htm)

Also there are such descriptions [for prosperity](http://www.citybuildingcontests.net/Caesar-Alan/The%20Appian%20Way%20-%20Prosperity%20Rating.htm), [peace](http://www.citybuildingcontests.net/Caesar-Alan/The%20Appian%20Way%20-%20Peace%20Rating.htm) and other ratings
