### ISSUE TITLE
Looking for different language versions of Caesar III game

### ISSUE THREAD

**Issue by gecube** [gecube/opencaesar3#144]
Does anybody have Caesar III distributions for French, Italian, German (Deutsch), Spanish (Español) languages? We will need original text files for making different translations. Also it can give useful information about game structure.

**Comment by ghost** [comment]
These files could possibly be obtained from the C3 patch files that were released. I noticed the English one has language text files in it, but I can't check the other languages until my VM finishes setting up (old 16 bit installers it looks like).

Also found this link somewhere which contains German text and WAV's (GOG forum maybe): http://www.2shared.com/file/tNQnCqKg/Caesar3_German_Files.html

**Comment by gecube** [comment]
@tracertong , I've unpacked patch files for different languages for Caesar III and found that patches aren't complete: they only makes changes in original text files. So original copy of Caesar III game is needed. Also thanks for link.
