### ISSUE TITLE
Detailed comments 

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#156]
Is necessary detailed comments in souce code or it undestand now???

**Comment by gecube** [comment]
Source code must be unambiguous so everybody can clearly understand what happens.
Of course, comments are good, but if they are actual and describe some pecular or unobvious things.
There is a lot of good articles about this topic, for example, on [habrahabr](http://habrahabr.ru/post/182574/)

**Comment by dalerank** [comment]
Ok set question from other side))) if some code seems to be hard for understand write about here.
