### ISSUE TITLE
Empire cities

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#157]
![1](https://f.cloud.github.com/assets/918081/720818/ebfde064-dfcb-11e2-9e80-4fe9ecb43805.png)

**Comment by dalerank** [comment]
![1](https://f.cloud.github.com/assets/918081/720820/1653d558-dfcc-11e2-840d-553b730fe024.png)
![1](https://f.cloud.github.com/assets/918081/720821/2ba582b2-dfcc-11e2-95b4-bafea8105958.png)
![1](https://f.cloud.github.com/assets/918081/720823/4831f988-dfcc-11e2-90bd-4267b2f9b6f2.png)
![1](https://f.cloud.github.com/assets/918081/720826/5ed4efe2-dfcc-11e2-97fd-1deca353f3e6.png)
![1](https://f.cloud.github.com/assets/918081/720829/6d7bf630-dfcc-11e2-8ade-c532c8f780c5.png)
![1](https://f.cloud.github.com/assets/918081/720832/7eda633a-dfcc-11e2-9bc6-1af375b2aecb.png)
![1](https://f.cloud.github.com/assets/918081/720835/9404b058-dfcc-11e2-98c3-0ba55a1bbcca.png)
![1](https://f.cloud.github.com/assets/918081/720837/a26a8fdc-dfcc-11e2-90c5-af25717019e5.png)
![1](https://f.cloud.github.com/assets/918081/720838/b77f840e-dfcc-11e2-8676-18b6b43b4c1d.png)
![1](https://f.cloud.github.com/assets/918081/720842/ce93d6fe-dfcc-11e2-9787-81b0ff75df73.png)
![1](https://f.cloud.github.com/assets/918081/720846/ef3ba738-dfcc-11e2-8e78-72dddea5feab.png)

**Comment by gecube** [comment]
As I understand, there are two types of cities: playable cities (which list you've made) and trade cities (their list is broader)

**Comment by dalerank** [comment]
Yes, now i put here description for playable cities.... those maps we can found in c3 resources

**Comment by dalerank** [comment]
Not for all cities i found params...

**Comment by gecube** [comment]
You've got information from there: http://caesar3.heavengames.com/downloads/showfile.php?fileid=867
