### ISSUE TITLE
Pathfinder for road build such original game

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#16]
Can somebody make normal pathfinder for build of roads, I couldn't use adaptive And \* for this. Thanks.

**Comment by gecube** [comment]
Pathfinder now is pain in ass. Because we will have also aqueducts (of course with underlying road), plazas and gardens, which all can be passed through by walkers.

**Comment by gathanase** [comment]
If the pathfinder makes use of some "isWalkable" tile property, that should
make things easier, wouldn't it?

**Comment by gecube** [comment]
Yes, it will be simpler. Also I've tried yesterday to change binding to Road\* to Construction\* in gathanase's pathfinder implementation - no success. 
P.s. I remember that granary and gatehouse can be passed through also.

**Comment by gathanase** [comment]
I think you need to change the binding to Tile_.
The "accessRoads" might need to change to Tile_ as well.

**Comment by dalerank** [comment]
gathanase, can you create pathfind alg for sawyer/hunter/emigrants???

**Comment by gathanase** [comment]
yes I will adapt the current algorithm.
I just need to understand how to work with git :-)

**Comment by gecube** [comment]
Work with git isn't complex. Please read http://www-cs-students.stanford.edu/~blynn/gitmagic/ It is useful reading.

**Comment by gathanase** [comment]
thanks for your link, that's better now!
I cannot merge my changes though (git keeps telling me i am not on a good
branch or something), I send you the patch instead.

there are two noticeable bugs when using all functionalities of the new
pathFinding:
- display glitch, I used "tile.is_flat" to draw walkable tiles first, but
  someone changed that so walkers are not well displayed on open land anymore
- full directions, some bug involving more than the 4 directions
  south/north/east/west.

**Comment by gecube** [comment]
@gathanase, I can explain problem with merging. It happens because our code now are very far from each other. So good idea is to (to you):
1. Make new branch in your repo
2. And fetch there content of dalerank:master or gecube:master
3. If there will be any conflicts - resolve them with overwriting old files by new.
Also you can create another local repo for our code.
git is very flexible, so there is many ways to solve problem and they all are 'right'.
