### ISSUE TITLE
boost::filesystem dependecies removed. need test on linux.

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#161]
I removed dependecies from boost. But tested on windows only, if any used linux os, please test on this too.
Thanks.

https://github.com/dalerank/opencaesar3/commit/546775ab89a5638bed0ba63faca3da37ad5a6a62

**Comment by dalerank** [comment]
fixed. tested on linuxmint 15
![oc3](https://f.cloud.github.com/assets/918081/753479/bc81b0ce-e569-11e2-9f91-038e19c1c561.png)

**Comment by akuskis** [comment]
Works fine on Centos 6.4 (cmake 2.6)

PS:
64bit linux
dalerank branch : commit b2427cecc09da386c44cf24db404a64783f0fea4 (where cmake was fixed for 2.6 version)

![screenshot](https://f.cloud.github.com/assets/3109998/772875/969e2438-e923-11e2-893c-effe4dfa10d7.png)
