### ISSUE TITLE
[bug] build_governor_palace_1 (segmentation fault)

### ISSUE THREAD

**Issue by akuskis** [gecube/opencaesar3#163]
Right click on building (on map) "build_governor_palace_1" leads to crash...

Tested on Windows and Centos 6.4

**Comment by akuskis** [comment]
core dump:

![screenshot-1](https://f.cloud.github.com/assets/3109998/773265/d860fd72-e933-11e2-93a2-2ccbdf8540db.png)

null pointer : LandOverlay::getType (this=0x0)

**Comment by dalerank** [comment]
fixed on commit d3913c774a214130c0579940fe5339cfe96b0282
