### ISSUE TITLE
[bug] building_aqueduct (corners must be rotated on 180 deg.)

### ISSUE THREAD

**Issue by akuskis** [gecube/opencaesar3#164]
Problems with corners.
![screenshot-2](https://f.cloud.github.com/assets/3109998/773511/5e8dc676-e93b-11e2-9d6f-d8e73a4bafb0.png)

**Comment by akuskis** [comment]
Now :
![screenshot-3](https://f.cloud.github.com/assets/3109998/774284/dd84f35c-e952-11e2-91e4-8e93b398cd51.png)

**Comment by dalerank** [comment]
win: work correct.
