### ISSUE TITLE
Market lady helper now work.

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#168]
Market lady go to granary.
![oc3_ 2013_06_12_10_48_34](https://f.cloud.github.com/assets/918081/786964/6b90953c-eacc-11e2-9b69-267f97872fa7.png)

uh... drag 4 bags with wheat very hard, but assistants already here
![oc3_ 2013_06_12_10_48_44](https://f.cloud.github.com/assets/918081/786965/8338518e-eacc-11e2-99ef-76bbf9d1f267.png)

**Comment by akuskis** [comment]
Nice, you have did a lot of changes for it.
