### ISSUE TITLE
Aqueducts

### ISSUE THREAD

**Issue by akuskis** [gecube/opencaesar3#169]
A lot of problems with Aqueducts...
![bug_1](https://f.cloud.github.com/assets/3109998/787925/f058d0a2-eaec-11e2-81ff-2c78a744d3ab.png)
![3](https://f.cloud.github.com/assets/3109998/787952/7d4b09bc-eaed-11e2-974e-2eba49d3a50f.png)

**Comment by akuskis** [comment]
Now they are nicer, but not at all.
![screenshot-opencaesar 3 0 2 560](https://f.cloud.github.com/assets/3109998/787984/172e039a-eaee-11e2-911a-e9874572903e.png)

**Comment by dalerank** [comment]
good work!

**Comment by akuskis** [comment]
Update logic... but need to fix something
![screenshot-opencaesar 3 0 2 560-1](https://f.cloud.github.com/assets/3109998/810048/056fc284-eea8-11e2-89a8-999fc62594ce.png)
