### ISSUE TITLE
[compile errors] Can't compile gecube/master branch

### ISSUE THREAD

**Issue by akuskis** [gecube/opencaesar3#171]
Checkout (commit 82e9171ab427ac3bf35b19c4be3823a36d424cb3) and try to compile gecube/master branch under Ubuntu... but got errors, like (sorry for Russian in log... it's computer of my girl):

№1
"/home/artuom/projects/game/opencaesar3/oc3_factory_building.cpp: В функции-члене «virtual void Factory::timeStep(long unsigned int)»:
/home/artuom/projects/game/opencaesar3/oc3_factory_building.cpp:131:73: ошибка: нет подходящей функции для вызова «SimpleGoodStore::store(GoodStock, int)»
/home/artuom/projects/game/opencaesar3/oc3_factory_building.cpp:131:73: замечание: candidate is:
/home/artuom/projects/game/opencaesar3/oc3_goodstore.hpp:61:16: замечание: virtual void GoodStore::store(GoodStock&, int)
/home/artuom/projects/game/opencaesar3/oc3_goodstore.hpp:61:16: замечание:   no known conversion for argument 1 from «GoodStock» to «GoodStock&»
/home/artuom/projects/game/opencaesar3/oc3_factory_building.cpp:167:76: ошибка: нет подходящей функции для вызова «SimpleGoodStore::retrieve(GoodStock, int)»
/home/artuom/projects/game/opencaesar3/oc3_factory_building.cpp:167:76: замечание: candidate is:
/home/artuom/projects/game/opencaesar3/oc3_goodstore.hpp:62:16: замечание: virtual void GoodStore::retrieve(GoodStock&, int)
/home/artuom/projects/game/opencaesar3/oc3_goodstore.hpp:62:16: замечание:   no known conversion for argument 1 from «GoodStock» to «GoodStock&»
make[2]: **\* [CMakeFiles/opencaesar3.dir/oc3_factory_building.cpp.o] Ошибка 1
make[1]: **\* [CMakeFiles/opencaesar3.dir/all] Ошибка 2
make: **\* [all] Ошибка 2"

№2
/home/artuom/projects/game/opencaesar3/oc3_advisor_finance_window.cpp: In constructor «AdvisorFinanceWindow::AdvisorFinanceWindow(CityPtr, Widget_, int)»:
/home/artuom/projects/game/opencaesar3/oc3_advisor_finance_window.cpp:80:122: ошибка: cannot pass objects of non-trivially-copyable type «class CityFunds» through «...»
make[2]: *_\* [CMakeFiles/opencaesar3.dir/oc3_advisor_finance_window.cpp.o] Ошибка 1
make[1]: **\* [CMakeFiles/opencaesar3.dir/all] Ошибка 2

....

They are simple, but it will be nice, if they will be fixed in master branch.

**Comment by dalerank** [comment]
fixed
