### ISSUE TITLE
[fault] __produceWater

### ISSUE THREAD

**Issue by akuskis** [gecube/opencaesar3#172]
Don't have a lot of time in this evening, so I'll show bug trace (sometimes i have this fault... (on map i have only "Well" and some buildings)):
#0  0x0818d244 in std::_Rb_tree<int, std::pair<int const, int>, std::_Select1st<std::pair<int const, int> >, std::less<int>, std::allocator<std::pair<int const, int> > >::_S_key (__x=0xea14120) at /usr/include/c++/4.6/bits/stl_tree.h:516
#1  0x0818c933 in std::_Rb_tree<int, std::pair<int const, int>, std::_Select1st<std::pair<int const, int> >, std::less<int>, std::allocator<std::pair<int const, int> > >::_M_lower_bound (this=0xea12dfc, __x=0xea14120, __y=0xea12e00, __k=@0xbf2c70f0: 700039)

```
at /usr/include/c++/4.6/bits/stl_tree.h:1090
```
#2  0x0818ba6a in std::_Rb_tree<int, std::pair<int const, int>, std::_Select1st<std::pair<int const, int> >, std::less<int>, std::allocator<std::pair<int const, int> > >::lower_bound (this=0xea12dfc, __k=@0xbf2c70f0: 700039)

```
at /usr/include/c++/4.6/bits/stl_tree.h:828
```
#3  0x0818b13d in std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >::lower_bound (this=0xea12dfc,

```
__x=@0xbf2c70f0: 700039) at /usr/include/c++/4.6/bits/stl_map.h:784
```
#4  0x0818a9e4 in std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >::operator[] (this=0xea12dfc,

```
__k=@0xbf2c70f0: 700039) at /usr/include/c++/4.6/bits/stl_map.h:450
```
#5  0x0826da13 in WaterSource::addWater (this=0xea12dd0, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:393
```
#6  0x0826ceaf in Aqueduct::addWater (this=0xea12dd0, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:267
```
#7  0x0826dd19 in WaterSource::_produceWater (this=0xea13108, points=0xbf2c71b0, size=4)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:433
```
#8  0x0826cf3e in Aqueduct::addWater (this=0xea13108, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:270
```
#9  0x0826dd19 in WaterSource::_produceWater (this=0xe440950, points=0xbf2c7240, size=4)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:433
```
#10 0x0826cf3e in Aqueduct::addWater (this=0xe440950, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:270
```
#11 0x0826dd19 in WaterSource::_produceWater (this=0xe440a08, points=0xbf2c72d0, size=4)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:433
```
#12 0x0826cf3e in Aqueduct::addWater (this=0xe440a08, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:270
```
#13 0x0826dd19 in WaterSource::_produceWater (this=0xea12c30, points=0xbf2c7360, size=4)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:433
```
#14 0x0826cf3e in Aqueduct::addWater (this=0xea12c30, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:270
```
#15 0x0826dd19 in WaterSource::_produceWater (this=0xea13210, points=0xbf2c73f0, size=4)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:433
```
#16 0x0826cf3e in Aqueduct::addWater (this=0xea13210, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:270
```
#17 0x0826dd19 in WaterSource::_produceWater (this=0xe433250, points=0xbf2c7480, size=4)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:433
```
#18 0x0826cf3e in Aqueduct::addWater (this=0xe433250, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:270
```
#19 0x0826dd19 in WaterSource::_produceWater (this=0xd6d0c78, points=0xbf2c7510, size=4)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:433
```
#20 0x0826cf3e in Aqueduct::addWater (this=0xd6d0c78, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:270
```
#21 0x0826dd19 in WaterSource::_produceWater (this=0xea14670, points=0xbf2c75a0, size=4)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:433
```
#22 0x0826cf3e in Aqueduct::addWater (this=0xea14670, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:270
```
#23 0x0826dd19 in WaterSource::_produceWater (this=0xea13db0, points=0xbf2c7630, size=4)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:433
```
#24 0x0826cf3e in Aqueduct::addWater (this=0xea13db0, source=...)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:270
```
#25 0x0826dd19 in WaterSource::_produceWater (this=0xea13e20, points=0xbf2c76c0, size=4)

```
at /home/artuom/projects/game/opencaesar3/oc3_water_buildings.cpp:433
```

I'll test it on gecube/master branch later... i think that whis problem is there too.

**Comment by dalerank** [comment]
fixed
