### ISSUE TITLE
[bug] logic of units

### ISSUE THREAD

**Issue by akuskis** [gecube/opencaesar3#173]
Want to mark here some bugs for future:
1. Units don't use roads if there is Aqueducts...
2. Units can go though Aqueducts...
3. Some units can't get out from area, if on road around they found aqueducts.

lol, need to find some time and done with aqueducts =)

![2013-07-16 19 51 11](https://f.cloud.github.com/assets/3109998/806212/d9b7ebd4-ee35-11e2-8c0f-40aba48cf1ff.png)

![2013-07-16 19 51 35](https://f.cloud.github.com/assets/3109998/806204/b2536e42-ee35-11e2-84fa-271b628031b7.png)

**Comment by dalerank** [comment]
ok... will try to fix

**Comment by dalerank** [comment]
![oc3_ 2013_06_16_22_40_10](https://f.cloud.github.com/assets/918081/807088/f6dfb6da-ee47-11e2-85be-1d76968a661f.png)
![oc3_ 2013_06_16_22_40_16](https://f.cloud.github.com/assets/918081/807090/fbdc5b2a-ee47-11e2-9105-7805d9858bb2.png)

**Comment by akuskis** [comment]
Good job, this commit must resolve it

**Comment by dalerank** [comment]
fixed
