### ISSUE TITLE
[fault] Pathfinder::aStar

### ISSUE THREAD

**Issue by akuskis** [gecube/opencaesar3#174]
Got a fault:

caesar3: /home/artuom/projects/game/opencaesar3/oc3_astarpathfinding.cpp:161: bool Pathfinder::aStar(const TilePos&, const TilePos&, const Size&, PathWay&, int): Проверочное утверждение «!(!child)» не выполнено.
Аварийный останов (core dumped)

But no core dump, on this bug... may be i'll show dump later, or fix it.
But any way, there is a bug.

**Comment by dalerank** [comment]
Fixed
