### ISSUE TITLE
Drawing text on transparent picture. How???

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#19]
Can any create example for drawing text in transparent surface???

**Comment by dalerank** [comment]
2gathanase. You better mean how to work with sdl. Can you write an example of drawing for text on a transparent background??? Thnks

**Comment by andreibranescu** [comment]
Maybe this will help:
http://stackoverflow.com/questions/3229391/sdl-sdl-ttf-transparent-blended-text

Look closely at the last example. I think that's the most pertinent one.

**Comment by dalerank** [comment]
thnks. i'll try it
