### ISSUE TITLE
autobuild add (travis-ci.org)

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#193]
Now you can see build result of current commit from my experimental branch here (http://travis-ci.org/dalerank/opencaesar3)

**Comment by gecube** [comment]
Super!

**Comment by dalerank** [comment]
Is somebody knows how upload artifacts from travis-ci.org and make archive, that other peoples could look at game???

**Comment by coniu** [comment]
http://about.travis-ci.org/blog/2012-12-18-travis-artifacts/

**Comment by AMDmi3** [comment]
There's another service you can use, called OpenSUSE build service: https://build.opensuse.org/
It creates package for different distros for you.

**Comment by dalerank** [comment]
can i build oc3 for other os???
