### ISSUE TITLE
Carriers stuck between two tiles

### ISSUE THREAD

**Issue by AMDmi3** [gecube/opencaesar3#201]
Here, carrier with pottery is just standing there, despite there's a warehouse (which was build after the carrier appeared though)
Carrier south to him is walking empty back and forth along the red line.

http://amdmi3.ru/files/c1.png

Same here, some moments later:

http://amdmi3.ru/files/c2.png

There's also a bunch of errors in the log, which mention out-of-bounds tiles, maybe unrelated:

```
No child for parent is (160,136)
ERROR: failed to gather point (160,137) on grid
No child for parent is (160,137)
ERROR: failed to gather point (-1,51) on grid
No child for parent is (-1,51)
ERROR: failed to gather point (-1,52) on grid
No child for parent is (-1,52)
```

**Comment by dalerank** [comment]
Warehouse can't work without stuff, may be rectuiter from wh not yer found peoples???

**Comment by dalerank** [comment]
yea... those msg from path propagator that can't create path correct in game map...  i know about this bug, but dont know how fix it

**Comment by AMDmi3** [comment]
> Warehouse can't work without stuff, may be rectuiter from wh not yer found peoples???

That is possible. We may drop that for now, the main problem is stuck carriers.

**Comment by dalerank** [comment]
fixed
