### ISSUE TITLE
House infobox now show condition for levelup.

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#210]
![oc3_ 2013_08_20_12_07_42](https://f.cloud.github.com/assets/918081/1179153/86d465d0-21cc-11e3-967f-79ba88e60ee2.png)

**Comment by andreibranescu** [comment]
Hi there,

I've been watching your commits and I wanted to say that you're doing a wonderful job. Thank you!

Sorry that I'm not able to contribute right now, I'm really busy.

Is there any milestone set for the next version?

**Comment by dalerank** [comment]
I do that i can, thanks... any yours changes will help this project. About creation of milestone it is better to ask gecube )))
