### ISSUE TITLE
Water and craches

### ISSUE THREAD

**Issue by captnfab** [gecube/opencaesar3#22]
- Building a reservoir on the border of the map makes the game crash
- buiding an aqueduct on a NE-SW road is not well rendered

**Comment by dalerank** [comment]
![aqueducts_bug](https://f.cloud.github.com/assets/918081/384784/e895942e-a666-11e2-9c78-f56d7b07f755.png)

**Comment by gecube** [comment]
Yes, there are problems. I know. Thanks. What I wrote is awful and early draft. But aqueducts pictures are almost working
