### ISSUE TITLE
Online installer

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#230]
Add online installer 
Linux version.
(http://sourceforge.net/projects/opencaesar3/files/bin/caesaria-ubnt-onln-2013_12_01.zip/download) 

Windows version.
(http://sourceforge.net/projects/opencaesar3/files/bin/caesaria-win-onln-2013_12_01.zip/download)

release repository placed in sf.net
installer check diff about your local and release folder and download needed files.

**Comment by malenka83** [comment]
pls, push src also ^_^
