### ISSUE TITLE
WT?F. Where source code??? 

### ISSUE THREAD

**Issue by malenka83** [gecube/opencaesar3#231]
Hi, gecube.
I see th you mv foss project to private repo, https://bitbucket.org/dalerank/caesaria and shared it on steam http://steamcommunity.com/sharedfiles/filedetails/?id=201200943&searchtext=
what hpned man? 
it so dfclt pull code here too? 

P.S. is it correctly use opensource prj like you own?
**NO FOSS, NO GREENLIGHT**

**Comment by gecube** [comment]
Hello!

Please, stay cool. You may ask @dalerank for all questions directly.

**Comment by malenka83** [comment]
"Hail, citizen. Have you heard? The gods are angry." (с)
i thought its your prj
hm, sorry

**Comment by gecube** [comment]
@malenka83 , :-) The original author of clone is http://sourceforge.net/users/greg3124 But he has a lack of time. So I take his code and begin to dig into it. Now I haven't spare time to develop game. So ath this moment @dalerank is most major contributor. It's Open Source, babe. Anybody can do anything (with known limitations ;))

**Comment by malenka83** [comment]
i saw, lot of commit was pushed from dalernk, is h still work around foss version, or rolldown to proprietary only? i send some mails 2 him, but ntsr that him readed are.  can you have contacts about?
FOSS is live!!!

P.S. greg n answer too : (

**Comment by dalerank** [comment]
English, please.

**Comment by antonlogvinov** [comment]
gecube, собираетесь ли вы выкладывать исходники caesaria?
как я понял это продолжение opencaesar ( взято отсюда http://www.linux.org.ru/news/games/10122991). Как можно принять участие в проекте? переписывать то что уже сделано у Вас, не очень хочется.
