### ISSUE TITLE
MacOS X support

### ISSUE THREAD

**Issue by brucelee1998** [gecube/opencaesar3#232]
Hi, gecube
Where i can found executable files for Mac OS X? 
i'm not a software engineer so have no any experience in coding, i try run game with winery, but it crashed before start menu, i want not using windows or other linux os.
Can you create build for my system Mac OS X 10.8.3, MacBook Pro ME864C/A?
Also i try send donation for your project, but can't find any information that i can do.
Thanks for your project, caesar3 was my first game on mac.

**Comment by dalerank** [comment]
good time, mac version under development yet...

**Comment by dalerank** [comment]
see here... http://sourceforge.net/projects/opencaesar3/files/bin/caesaria-osx-10.8_64-2014_02_14.zip/download
