### ISSUE TITLE
Where source code now

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#234]
You can find source code on bitbucket https://bitbucket.org/dalerank/caesaria

I didn't appropriate source codes as some here wrote(https://github.com/gecube/opencaesar3/issues/231) that began as the opensource project will be opensource and further. If it is interesting to you to develop together, join me on bitbucket.

Why bitbucket:
- I use bitbucket+jira more long than github
- it is possible to do full build on drone.io
- unlimited disk place

**Comment by andreibranescu** [comment]
Thanks for the info. Love the job you did on the project so far.

**Comment by Mailaender** [comment]
You have not tagged any releases yet. Using branches for it https://github.com/gecube/opencaesar3/tree/v.0.2 is a bad idea.

**Comment by dalerank** [comment]
Last stable revision here (https://bitbucket.org/dalerank/caesaria/branch/stable)

**Comment by Mailaender** [comment]
It is confusing that http://opencaesar3.org redirects here while you actually moved to bitbucket.org and https://github.com/gecube/opencaesar3#releases announces releases while in fact: there are none https://github.com/gecube/opencaesar3/releases tagged.

**Comment by dalerank** [comment]
yes man, but i havenot access to opencaesar3.org... but opencaesar3.org redirect here is true, bitbucket have fork which called CaesarIA, 1C-games sent message that Caesar III or 3 is registered trade mark and it not be possible in other names.
