### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#235]
**test build for Andorid**
http://sourceforge.net/projects/opencaesar3/files/bin/caesaria-android-test.apk/download

**bad**
- is ported "as is" without features of work on the tablet PC
- to press the button it is necessary "tap" twice on the screen, the first time moving to the screen point, the second pressing actually presses the button
- in total small elements though on the personal computer 
- slowly (((on my sgh-i957 gives out 10-12 fps

notplayable, experiments only

![2014-03-15-721.jpg](https://bitbucket.org/repo/gxxkpE/images/65332096-2014-03-15-721.jpg)
![2014-03-15-727.jpg](https://bitbucket.org/repo/gxxkpE/images/2339572547-2014-03-15-727.jpg)![2014-03-15-722.jpg](https://bitbucket.org/repo/gxxkpE/images/3483206808-2014-03-15-722.jpg)

**Comment by gecube** [comment]
cool!
