### ISSUE TITLE
2AntonBaracuda: change git-name please

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#239]
Уважаемый Антон, пожалуйста, смените вашу подпись в гите. Нехорошо чужие ники воровать.
С уважением,  Dalerank

**Comment by AntonBaracuda** [comment]
слышь старичок мне глубоко похуй на твое нытье как хочу так и комичу уж кто и должен сменить ник так это ты нехорошо чужие исходники воровать
без уважения антон баракуда

**Comment by dalerank** [comment]
Don't fixed

**Comment by AntonBaracuda** [comment]
Хуле топик закрыл правда глаза колет
