### ISSUE TITLE
Garden

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#27]
Is need to tile know that it is a garden???

**Comment by dalerank** [comment]
I think garden it same building such others.

**Comment by andreibranescu** [comment]
I think it should be a sepparate kind of building, or something similar to Granary. They are walkable in Caesar 3.

**Comment by gecube** [comment]
Now there are two things telling to us that tile is garden:
IsGarden() function and type of overlay.
Also gardens are walkable like roads and plazas. And gardens are shown on desirability map (maybe I'm wrong, but on one kind of layers, gardens are showed).
Also gardens can't be destroyed by enemies and they have no need in prefects and engineers for normal working: gardens can't be burned down and they have no chance of collapse.

**Comment by dalerank** [comment]
Is it mean that the garden is road but with different picture???

**Comment by gecube** [comment]
No. Gardens are different from roads. Plane empty tile is also walkable by walkers, but you won't say that plain tile is "road".
Differences with roads:
- gardens can be walkable, but the paths with roads are more preferred;
- gardens changes desirability, roads - don't
- gardens can be grouped into 2*2 tiles, but this is "virtual" and is ised only when drawing tiles
- roads have directions, gardens - don't
- one can't build aqueduct over garden, but you can build aqueduct over road (there are some exceptions)
- roads can be upgraded to plazas, gardens can't.

Differences with buildings:
- gardens don't require workers
- gardens can't be destroyed (by enemies)
- gardens aren't affected by fire, epidemic. They have no chance of collapsing
- gardens don't provide any service - they only change desirability (as common buildings)

**Comment by gecube** [comment]
Also I want to discuss one thing. For example, we calculate path for walker. And the road tile from its path is destroyed. We must to decide what to do. 
- walker can go back
- walker can dissappear
- walker can go through empty tile as there is road
- or we can recalculate all path and walker will use other roads (in case when there are no roads to destination look on previous variants).
  Also as walkers are slow we can trap them, for example, creating square of aqueducts amd walls. We must handle such situation too.

**Comment by captnfab** [comment]
We can either 
- stick to C3 behavior: walker walks on empty tiles. It won't be a solution if a building has been created meanwhile, and I don't remember what happens in original C3 in this situation
- check in real-time : when a walker is on a tile and going into one of the neighboring tiles, check first if the tile is walkable (or walkable & not empty space) and if it is, continue, otherwise, recompute path, and if no available path, disappear after some timeout.

Making walkers disappear is always dangerous since they can disappear with the resources they are carrying.

**Comment by dalerank** [comment]
ok... i understand my mistake

**Comment by gathanase** [comment]
It would be really nice to have walkers recompute the path, and walk on
empty tiles slowly. If there is no valid path to their destination they
should suicide and reappear near their origin with the same resources.
The cost of a walk on some tile may depend on the tile being a
road/garden/empty tile/ruin/..., that cost would influence the speed of the
walker on that tile. The pathFinding algorithm can be easily adapted to
have various tile costs.

I will adapt the walker speed and the pathFinding algorithm.
