### ISSUE TITLE
Walkers. Separate from garden

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#28]
1 . Walkers who can go without roads (the hunter, the emigrant, the military)
2 . Walkers who (porters) can't go without roads

Is it good idea???

**Comment by dalerank** [comment]
People have some point of lives, I so thought when played original game.When in city was a hunger, some people died. We can make also that the locked porter could die by hunger, then resources too will be gone. If pusher is locked, it can periodically check that there was a new road or not.

**Comment by gecube** [comment]
Good. Also we must realize difference between one walker in different situations.
For example, let take prefect. When he is patroling streets, he moves only by roads, but when he is fighting with fire he can move to burning building closely through empty tiles and gardens.

**Comment by captnfab** [comment]
Yep. And also... prefects (and other walkers) may die (for example against wolves, soldiers or angry citizens) it this case, they must be "automagicaly regenerated", except for soldiers and migrants)…

**Comment by gecube** [comment]
Yessss. And now there is glitch: walkers are generated independently to their number. For example, in original fame there can be only one prefect from one prefecture. In our project game potentially can produce any number prefects from one prefecture. Such thing takes place with cart pushers: in original game this behaviour makes need of stocks near industrial buildings, or production will stop...

**Comment by dalerank** [comment]
prefecture can make only one prefect, but his skill of fire fihgting calc as workers/5. Then partially filled prefecture will make prefects with a smaller productivity. Or the second way, the is less than workers in prefecture the more rare it to make prefects, it is easier

**Comment by captnfab** [comment]
And to avoid generating too much / not enough prefects, we add some TimeToLive to the walkers, and they disapear once it reaches 0 ?

**Comment by dalerank** [comment]
Can make the prefect, only if the prefecture already has no prefect on watch???
If the prefect can't will return to prefecture to eat:))) (TimeToLive), he will die through some time, having given a signal to the prefecture about this event

**Comment by captnfab** [comment]
- I understood from what gecube said that a building does not keep track of the walkers it generates.
- AFAIK, there is no « death by hunger » , but the TTL can replace that.

**Comment by gecube** [comment]
@captnfab
You are right. In original game, one prefecture - one or zero (between generations) prefect. TTL will be enough, I think. Also player can free captured walker by destroying some building.

**Comment by gathanase** [comment]
If I am not mistaken, serviceWalkers already have some kind TTL: that's the
number of tiles they can go.
