### ISSUE TITLE
Is hard to create non square building???

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#29]
Such really nonsquare building, but hippodrome are 3 buildings, not one

**Comment by gecube** [comment]
Yes, you are right.
I see two approaches:
- make buildings which are parts of "big" builduing with different IDs. In buildings class store pointers to next segment.
- or make buildings class able to contain different number of objects of subclass "part of building"

Also such building with two or more parts are forts: they consist from 3x3 main part and 4x4 platz.

**Comment by andreibranescu** [comment]
Why do we need non-square buildings?

**Comment by gecube** [comment]
Because there are al least two such buildings:
- hippodrome (3 blocks of 5x5 tiles)
  and
- forts (3x3 + 4x4)
  I have no information about another non-square. Maybe there aren't such in game.

**Comment by andreibranescu** [comment]
Evidently... I don't know why, but I understood rectangular buildings. 
Never mind. :)
