### ISSUE TITLE
Wrong build. How fix???

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#31]
![build_bug](https://f.cloud.github.com/assets/918081/396528/21e59e78-a828-11e2-8f93-4181e2fef344.png)
![build_bug2](https://f.cloud.github.com/assets/918081/396529/21ffe710-a828-11e2-8297-357b2e3efee4.png)

**Comment by gecube** [comment]
You can try to detect overlay picture ID and when it says that overlay contains elevation trigger isConstructible or analogical flag. Look at code of generating natives huts. The principle is similar. The difference is in type of tile: native huts are buildings and elevation is... I don't know what is it. But we can find out it by creating empty map in scenario editor with such type of elements and then opening map in hex-editor and looking at raw bytes...

**Comment by dalerank** [comment]
ok... thanks. May be set those tiles not constructible???

**Comment by gathanase** [comment]
The so called "access ramp" flag is written in the scenario file similarly
to trees/rock/water/..., so we may put that information in the TerrainTile
objects and use that in the isConstructible method.

**Comment by dalerank** [comment]
can you set flag road for those tiles??? or say where i can found this code. thanks

**Comment by gecube** [comment]
Check https://github.com/gecube/opencaesar3/blob/master/oc3_scenario_loader.cpp file
