### ISSUE TITLE
BUG: when deleting building, original land tile is lost

### ISSUE THREAD

**Issue by gecube** [gecube/opencaesar3#34]
![before](https://f.cloud.github.com/assets/2912732/399637/e1c137d4-a878-11e2-82e5-ad6465a5f154.png)
![after](https://f.cloud.github.com/assets/2912732/399639/e78facb8-a878-11e2-910a-f8a9394f8d7d.png)

The bug appears because when building is deleted, the terrain tile is randomly generated by game. But it is bad behaviour: the state of tile must be saved, i.e. if it was fertile tile - tile must be fertile too after building removing. I'm talking about tiles, not about their content (trees, bushes and so on).

Also sometimes remove tool is glitching. It doesn't delete all buildings in rectangular area of selection....

P.S. I want to have debug feature: to see original data from original file in infobox when right-clicking on tile. I've just developed such feature, but it doesn't work perfect. I won't upload it in next hours until I will understand that it is fine.

**Comment by dalerank** [comment]
i known about this bug, but i can't fix it yet ((( i don't known how

**Comment by gecube** [comment]
Partially solved...

**Comment by dalerank** [comment]
Fixed

**Comment by gecube** [comment]
When one deletes native buildings (native hut, native center, native field) it is replaced with "empty" black tile. 
As I understand, in original game such buildings cann't be deleted and works as special land tiles. But I think that they are 100% buildings, so we need to decide what type of terrain tile will be under them. After that we can decide make these buildings destroyable by player or not. I think that behaviour can be changed. For example, we can make compatibility mode, when native buildings works as in original game, and enhanced mode, when they works slightly different (if we destroy native huts, natives will become angry and send one legion to attack us :-)).

**Comment by dalerank** [comment]
fixed... native building's more can't be destroyed
