### ISSUE TITLE
BUG: when deleting building, the tiles to north-east are cleared too

### ISSUE THREAD

**Issue by gecube** [gecube/opencaesar3#36]
![before](https://f.cloud.github.com/assets/2912732/404426/98e82b88-a947-11e2-8c9b-ec16062d63ed.png)
![after](https://f.cloud.github.com/assets/2912732/404431/a97a1dda-a947-11e2-90bd-8b45dfc862a2.png)

**Comment by dalerank** [comment]
This code also present in project. See virtual building::destroy function

**Comment by gecube** [comment]
Solved.
