### ISSUE TITLE
Employment of workers

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#43]
Step first. People arrive to the city

![9](https://f.cloud.github.com/assets/918081/414802/14045e26-ac23-11e2-8e1b-aed8892581bd.png)

Step second. When placed prefecture or the engineer through some time starting service of hiring workers and from the prefecture will be produced a hunter. The picture is taken from the librarian, can it is worth making him invisible. In original game the building left the same type of characters who provide service, only it not provided service but people employed.
![10](https://f.cloud.github.com/assets/918081/414811/37141c44-ac23-11e2-9f54-70b6a3b7e0a0.png)

Step third. When people are hired, prefecture start work and produce native workers.
![11](https://f.cloud.github.com/assets/918081/414836/c4c491ea-ac23-11e2-9932-de93cca214f4.png)

**Comment by andreibranescu** [comment]
Are the second and third steps completed yet?

**Comment by dalerank** [comment]
yes, all steps are completed.

**Comment by andreibranescu** [comment]
Ah, cool!

**Comment by gecube** [comment]
The hirer (recruiter) is typical citizen and picture for it is from citizen01.bmp range [1;104]
Also it is needed to be fixed: picture for market boys (they aren't scholars) and I don't remember what :-)

**Comment by andreibranescu** [comment]
Yeah, I notice that, but it's not important. What's important is their behaviour. The image can be changed pretty quickly.

**Comment by andreibranescu** [comment]
I've just fixed the two you mentioned.
