### ISSUE TITLE
Now house able update to second level.

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#44]
pls test for bugs.

Build 4 huts.
![12](https://f.cloud.github.com/assets/918081/419934/c7a0564c-ace1-11e2-89d8-6bb04235f8b7.png)

When well build. house update to 2 level
![14](https://f.cloud.github.com/assets/918081/419935/d5a462d8-ace1-11e2-95fd-6f8778e1c66d.png)

Check info
![15](https://f.cloud.github.com/assets/918081/419941/f6ef3fda-ace1-11e2-91b5-cdfe62cacf43.png)

**Comment by dalerank** [comment]
Andrei, can you create third and four level update for house???

**Comment by andreibranescu** [comment]
Good idea, I will try.
