### ISSUE TITLE
Prefect fights with fire. Any ideas how to make???

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#46]

**Comment by gecube** [comment]
Yes, I have such.
- every fire has it's own "hitpoints"
- with every tick fire decreases it's hitpoints counter
- every prefect with water bucket decreases fire hitpoint by one
- when hitpoints is zero, burning stops

**Comment by dalerank** [comment]
ok... i see that one prefect can stop only 2 fires... what you think about???

**Comment by gecube** [comment]
OK. Prefects must have health points too :-)

**Comment by DarkLotus** [comment]
Have fire spread via celluar automata? 2 fire cells = create a 3rd, more than 3 have one die. incorperated with prefects having HP/fire having HP?

**Comment by dalerank** [comment]
I think the mechanism of fire distribution more simply, each cell of fire raises Building::_fireDamage gain in the next cages much therefore and cell around light up quicker.

**Comment by andreibranescu** [comment]
I say we should try to replicate the behaviour of fires and preferects from the original game. I will try to find how it's implemented.

**Comment by dalerank** [comment]
yes... i already work for it
