### ISSUE TITLE
Increase maxDistance for Prefect/Engineer. What you think??? 

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#47]

**Comment by gasobi** [comment]
What will it give?

**Comment by andreibranescu** [comment]
I think we should increase the max distance. It's too small now.

**Comment by andreibranescu** [comment]
Increasing the maximum distance of the prefect's range will make it visit more houses before it returns to its post. Now it's actually pretty short, which forces you to construct a lot of prefectures to cover a larger area of houses.
