### ISSUE TITLE
Is need self basic variable types???

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#48]
Such here???
//! 8 bit unsigned variable.
/*\* This is a typedef for unsigned char, it ensures portability of the engine. */
# ifdef _MSC_VER

```
typedef unsigned __int8     u8;
```
# else

```
typedef unsigned char       u8;
```
# endif

//! 8 bit signed variable.
/*\* This is a typedef for signed char, it ensures portability of the engine. */
# ifdef _MSC_VER

```
typedef __int8          s8;
```
# else

```
typedef signed char     s8;
```
# endif

//! 8 bit character variable.
/*\* This is a typedef for char, it ensures portability of the engine. */
typedef char            c8;

Or use sdl types???

**Comment by gecube** [comment]
I don't like such stuff. In any case, we can use SDL types or use types from <stdint.h>
