### ISSUE TITLE
Clay pit

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#51]

**Comment by gecube** [comment]
What do you mean? Clay pit must produce clay with some speed. This speed depends on number of workers. When production is complete, clay pit generates cart pusher which moves to nearest available warehouse. Or if you would like, clay pit may directrly supply ceramics workshops :-)

**Comment by dalerank** [comment]
yes... i see in game, that cart pusher from clay pit go to ceramics workshops passing warehouse. and i think how do it here.

**Comment by andreibranescu** [comment]
I think that the code can be copied from the farms, and you can make a superclass for all the raw materials. The behaviour of clay pit is almost the same as the behaviour of iron mine, for example.

**Comment by dalerank** [comment]
good idea, thanks

**Comment by gasobi** [comment]
Also one thing to mention. When cart pusher is generated, clay pit doesn't stop producing clay. So situation when cart pusher hasn't returned and production is in clay pit is possible. In such case clay pit must not to generate second cart pusher, but wait until first will return.

**Comment by dalerank** [comment]
1. Is clay pit have only once cart? 
2. Only full cart may be generated or partly too?
3. What need do with cart if clay pit have was destroyed ?  Cart in half way to warehouse, forexample. 
4. Cart walk only road or all terrain?
   Thanks

**Comment by gasobi** [comment]
1. yes
2. Only full cart can be generated. (full cart = at least one item of clay)
3. Cart must go to warehouse and then disappear
4. Cart walk any road + granary + arch + plazas + roads with aqueducts. If path to destination was destroyed, cart may (or may not) use any walkable terrain tile.

**Comment by dalerank** [comment]
Create clay pit.
![18](https://f.cloud.github.com/assets/918081/450159/bfd10eea-b289-11e2-9c86-3b2d361cab1e.png)

Build warehouse for clay. Cart pusher go to warehouse. And clay stop working but have once cart pusher.
![19](https://f.cloud.github.com/assets/918081/450164/cbd53658-b289-11e2-877a-fd28a4a1fa59.png)

Cart pusher return to clay pit for new portion.
![20](https://f.cloud.github.com/assets/918081/450172/eff5e366-b289-11e2-90ea-7763eb9d968b.png)

**Comment by gecube** [comment]
Excellent! The only thing is need to be done : correct magic values for 
- speed of cart pusher
- speed of clay generating
