### ISSUE TITLE
Build issues on windows after recent commits

### ISSUE THREAD

**Issue by ghost** [gecube/opencaesar3#55]
oc3_factorymarble.\* files are missing from visual studio project

Below code from o3_positioni.hpp gives linking errors, had to move it out from header to source file to compile in vs2008

``` C++
std::ostream & operator << (std::ostream& os, const TilePos& tp)
{
  return os << "(" << tp.getI() << "," << tp.getJ() << ")";
}
```

**Comment by dalerank** [comment]
yes... under vstudio have this error... add "inline" before function... or pull my revision.

**Comment by gecube** [comment]
Sorry, but I can't check if project works in VS. If you can, please fix problems and then I will include your changes into my repo
Or you may use dalerank repo. He develop under VS, so there must be no problem with his code.

It is pity that we need a lot of efforts to make code working in both gcc and MSVS

**Comment by ghost** [comment]
Maybe it's good idea to use something like cmake? 

And another one, could be good if build decencies and resources (and I don't think you should provide resource from original game till you have permission from copyright owner to do so ) can be provided as separate download.

**Comment by gecube** [comment]
> Maybe it's good idea to use something like cmake?

Maybe.  I like idea of trying different tools to find best option. Please, try to give example of cmake file for our project. And we will test it. Thanks.

**Comment by ghost** [comment]
I'm not best experienced on it, I will try :)

**Comment by dalerank** [comment]
Can you speak russian???. It seems that you from kz. my skype : dalerank[нижнее подчеркивание]pda

**Comment by ghost** [comment]
> Can you speak russian???. It seems that you from kz. my skype : dalerank[нижнее подчеркивание]pda

Sure, you are in the skype now.

> Please, try to give example of cmake file for our project. And we will test it.

Looks like I have something to give you for a test https://github.com/hellium/opencaesar3/tree/cmake There is a small guide https://github.com/hellium/opencaesar3/blob/cmake/BuildingOpenCaesar3.md , tried my best, don't blame me for it :) 

I did register opencaesar3.org pointing to your github project, just to reserve a name.

I did a few changes on you branch, and some of them are just my vision, but it could be a good practice to:
- Keep resource data outside source code repository (I also moved font file)
- Same goes for build dependencies
- Same goes for everyone's best IDE project files
  - add your IDE/build system files to .gitignore
  - or keep them outside code repository folder

Anyway try CMake in work, if you like it we can integrate, other "changes" are optional and are matter of taste.

**Comment by ghost** [comment]
- [x] Build system on windows now copies *.dll to opencaesar3.exe file directory as PRE-BUILD action.
- [x] -R <resource-path> is now set for Visual Studio project automatically. You can execute "debug" action with no extra steps.
- [ ] Make install target to create folder ready for distribution.
- [ ] Possibly automate execution of NSIS on Windows, and something on Linux too
- [ ] Add more customizations for QtCreator and Eclipse build environments
- [ ] Add more entries to .gitignore

**Comment by gecube** [comment]
Fantastic! I analyzed situation and have found that CMake is good.
Also please contact with me through skype, my account is rooter51

**Comment by ghost** [comment]
added you in skype. Do you also speak Russian?

**Comment by gecube** [comment]
Thanks. Better than you think :-)

**Comment by ghost** [comment]
What tools (OS/IDE/Compilers) do you use for development? I will modify guide and optimize cmake scripts for it.

**Comment by dalerank** [comment]
1. WinXp/vs2008
2. Win7/vs2008
3. LinuxMint/qtcreator2.7 (optional)

**Comment by gecube** [comment]
OpenSUSE 12.3/none/g++ (SUSE Linux) 4.7.2 20130108 [gcc-4_7-branch revision 195012]

**Comment by gecube** [comment]
I think it is good idea to add next flags to cmake file:
- `Wall` - to see all warnings from compiler
- `-g` - for g++, make debug information, so stack trace in gdb will tell about particular line in source code

Maybe you have such ideas too. Please share them with us.
