### ISSUE TITLE
libarchive

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#57]
Is so need use libarchive or may use native zlib? I looked code and for me seems that libarchive it intermediary between the program and zlib. Whether it is necessary to clean it and to use at once zlib? less dependecies will.

**Comment by gecube** [comment]
Does zlib support 7z and bzip formats? If "yes", then you may try to use zlib, in another case - please leave compression support as it done now.

**Comment by dalerank** [comment]
yes... 7z, arj, bzip2, gzip, tar, wim and xz

**Comment by gecube** [comment]
OK. Let's use zlib.
