### ISSUE TITLE
Native buildings 

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#58]
From gecube.
"
When one deletes native buildings (native hut, native center, native field) it is replaced with "empty" black tile. As I understand, in original game such buildings cann't be deleted and works as special land tiles. But I think that they are 100% buildings, so we need to decide what type of terrain tile will be under them. After that we can decide make these buildings destroyable by player or not. I think that behaviour can be changed. For example, we can make compatibility mode, when native buildings works as in original game, and enhanced mode, when they works slightly different (if we destroy native huts, natives will become angry and send one legion to attack us :-)).
"

**Comment by gecube** [comment]
Please tag (label) issues :-)

**Comment by dalerank** [comment]
I think now those native building must be unbreakable. Later you can decide what behavior those.

**Comment by dalerank** [comment]
How???

**Comment by gecube** [comment]
> How???

On right side there is button "Labels" with gear icon. Click and select necessary labels.

> I think now those native building must be unbreakable. Later you can decide what behavior those.

OK. Good. But now we suppose that these buildings lay on "flat ground tile". Please fix.

**Comment by dalerank** [comment]
ok... i'll try fix this bug

**Comment by dalerank** [comment]
Fail. no gear.

![21](https://f.cloud.github.com/assets/918081/470091/4fe73f1c-b6eb-11e2-8de5-59012500e032.png)

**Comment by gecube** [comment]
![gear](https://f.cloud.github.com/assets/2912732/470102/a05a43e0-b6eb-11e2-869a-9e67f0f000b9.png)

**Comment by dalerank** [comment]
you boss)))

**Comment by gecube** [comment]
Also native buildings can't burn down or collapse.

**Comment by dalerank** [comment]
fixed
