### ISSUE TITLE
BUG: when trying to add house or use remove tool

### ISSUE THREAD

**Issue by gecube** [gecube/opencaesar3#59]
When trying to add house or use remove tool, then rectangle are started from coordinates of earlier pressed button.
So I can't make rectangle in the centre of map. Looks like it is regression
Also such problem exists with roads and aqueducts.

![regression](https://f.cloud.github.com/assets/2912732/474058/aa9ebe22-b75d-11e2-8346-b8affbb02e1c.png)

**Comment by dalerank** [comment]
yes... i know about bug... but don't undestand how fix it now

**Comment by gecube** [comment]
I think that problem lays here: when you click on empty space of right bar, message about clicking is redirected to tilemap. This is erroneous. When somebody clicks on right menu in place between and around of buttons, click message must be consumed and nothing must happen.

**Comment by ghost** [comment]
Please check above commit, should resolve the issue. By default event will not be forwarded from GUI to Tiles even if it was not handled in GUI widgets.

**Comment by dalerank** [comment]
thanks

**Comment by dalerank** [comment]
fixed
