### ISSUE TITLE
Need Roadmap

### ISSUE THREAD

**Issue by captnfab** [gecube/opencaesar3#6]
Hi, I would like to (try to) contribute to this project. It would be nice if one of the lead developpers / lead forkers who already studied (a good part of) the code could write a wiki page containing the RoadMap : what's done, and what remains to do. 
There might also be some refactoring or reorganization of the code to do?

**Comment by gecube** [comment]
Hello!

This is great idea. The goal of project is to reimplement all features of original game, Caesar III. We need to know all them all, but at this point there isn't full understanding what need to do. One can try to run original game and find what we need.
Of course, I'll try to make some kind of roadmap or feature list in next few days. I hope that this will help in developing.

**Comment by captnfab** [comment]
Thanks for your reply :)
Yes, I think it's important to have a global view of how the game is designed in order to be able to plan the development and to share the different tasks.

**Comment by captnfab** [comment]
I created a wiki page to list the (un)implemented features : https://github.com/gecube/opencaesar3/wiki/State-of-the-art

**Comment by captnfab** [comment]
With your publication on the Wiki, this issue is closed : https://github.com/gecube/opencaesar3/wiki/RoadMap
Thanks \o/
