### ISSUE TITLE
BUG: arrows on the edge of map

### ISSUE THREAD

**Issue by gecube** [gecube/opencaesar3#60]
There are to things to be mentioned
1. In original game arrows point to edge of map.
2. In original game arrows are located (when using standard map orientation - North is on top) on tile top to road tile. Also there are sometimes gap between blue arrow and the edge of map. The size of gap is one tile. I don't understand the reason of such gap's existense 

![arrow](https://f.cloud.github.com/assets/2912732/474320/0c1c5676-b765-11e2-9b49-28bb956dac0e.png)
![original game](https://f.cloud.github.com/assets/2912732/474321/17babf22-b765-11e2-8c45-35b5eea6c355.png)

**Comment by dalerank** [comment]
I think it not so major bug and if it doesn't crash programm, then let's postpone it as a defect and it is reparable when more serious problems will be solved...

**Comment by gecube** [comment]
OK. It is not very important, but is annoying. So let's remember that this problem exists.
