### ISSUE TITLE
BUG: House bug. Dn't understand how fix.

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#62]
![1](https://f.cloud.github.com/assets/918081/489230/6741e9da-b995-11e2-85a2-d31b1e57db8b.jpg)

**Comment by gecube** [comment]
When degrade house, we must check if it will become bigger number of smaller houses. Then we must build on "black" tiles houses of correct levels

**Comment by dalerank** [comment]
yes... i know... i did it for 3->2, but it don't work for 4->3... hmm... may be error anywhere else

**Comment by dalerank** [comment]
fixed
