### ISSUE TITLE
Non-Free content

### ISSUE THREAD

**Issue by captnfab** [gecube/opencaesar3#7]
The "resources" folder contains non-free non-redistribuable files and therefore should not be published here. We should remove the folder and do 1 and/or 2
1. replace it with (dummy) free content
2. add a script that creates a ressources/ directory from the data1.cab original file.

**Comment by gecube** [comment]
Hello!

There are at least 3 ways what to do. You forget to add that we can communicate to copyright holders and ask their permission to use resources from original game (not done yet).
Also I'll reply to yours two paths:
1. There are no dummy content. One will need to rewrite everything. It is possible but very-very difficult. And this can be made when opencaesar3 will be finished :-)
2. There is such script. Please take a look to install.sh script : https://github.com/gecube/opencaesar3/blob/gregoire/install.sh
Also I add some code to sgreader for convenient way of unpacking resources from original game.

**Comment by captnfab** [comment]
You're right about 3. Ask the copyright holders :) But I believe the only way to make opencaesar3 _free_ will be with 1.

For 2. Yes, I've seen this script, but it is still incomplete. I had also patched sgreader for command-line use. I'll try your version since it uses cleaner C++ :)

(This doesn't change the fact that for now, the non-redistribuable content should be removed from public access)

Finally, not all files from sgreader have the GPL header, but I think we can safely assume that all the code is GPL-licenced?

**Comment by gecube** [comment]
- When did you try to make console version of sgreader? Before my attempt or after?
- What files from sgreader don't have GPL header? As I remember all project is licensed under GPL.
- Also is good idea to put sgreader into SUBmodule of repository, because it is related to opencaesar3, but different project from different author (in original)...

**Comment by captnfab** [comment]
- I did the console version of sgreader yesterday, before knowing this github project existed. Here are my changes : https://github.com/captnfab/opencaesar3/tree/old/old (it the n-1 version, from my backups, since I deleted everything when I saw this project)

There is also an "import.sh" script: an improved version of the "install.sh" script, using my modified version of sgreader.
- mainwindow.\* has no GLP header, "sgfile.*" neither...
- I totally agree with you on putting sgreader as a separated submodule.

**Comment by gecube** [comment]
@captnfab , I have different command line options. Please check what need to be fixed in import.sh

**Comment by andreibranescu** [comment]
Asking the copyright holders for their permission over the content is a great idea. If I'm not mistaken, the current copyright owner is Activision. We should send them an email asking them if they would be kind enough to pass the content in a CC license so that we can redistribute it.

**Comment by Rovanion** [comment]
@andreibranescu Just reading off Wikipedia it seems as if it's Vivendi SA which holds the rights to Caesar III since they bought it from Candant who bought it from Sierra, a subsidiary of Activision.

Now Vivendi SA is major part owner of Activision Blizzard which could mean that the rights have been passed down to their subsidiary. But I really have no idea.

**Comment by gecube** [comment]
Now resources are cutted off from repository. Please look for instructions where to download resources in the file "resources/README"
