### ISSUE TITLE
Is need VFS in project???

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#72]

**Comment by dalerank** [comment]
I have impl for virtual file system, is it need in this project???

possibilities:
1. Some archives instead of a huge number of small files
2. Possibility of a debugging
3. Pluggable Encryption and Compression ( Archive, zip, 7z etc with access as file)
4. Security ( if needed ) (in the vfs file MD5 a key is stored so any changes of archive will be right there noticed)
5. Some root of ways (alias)
6. Filters, find and enumerate files 
7. Simple access for any files ( archive, memory, hdd, network )

**Comment by gecube** [comment]
Hello!

I don't think that we need such features. Maybe later, when project'll become larger
