### ISSUE TITLE
BUG: animation + selection

### ISSUE THREAD

**Issue by gecube** [gecube/opencaesar3#73]
If one select remove tool, he will see some bus:
- problems in order of building pictures drawing (some top buildings are drawn over some bottom building);
- remove building picture doesn't show animation, but if you'll look carefully, in some places parts of animation can be recognized (look at left corner of selection);
- problems with some buildings pictures (ex.: warehouse);

![bug_with_selection](https://f.cloud.github.com/assets/2912732/512199/c9380832-be1c-11e2-8ae2-21a64a73d3cc.png)

**Comment by dalerank** [comment]
Fixed.
