### ISSUE TITLE
Screenshot (by f10/f12 pressed)

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#80]
need implement.

**Comment by gecube** [comment]
Please do not bind anything to PrintScreen key. I ask you because in Linux there aren't any problems with taking screenshots.

Also I offer to use some of F-keys to take in-game screenshots. Maybe F10 or F12.

**Comment by gecube** [comment]
I've just implemented taking of screenshots. It is easy and real work is made by SDL_SaveBMP function.

It is bad but I've lost connection to internet so I will be able to upload code only tomorrow.

**Comment by dalerank** [comment]
ok... can you save it to png???

**Comment by gecube** [comment]
Yes, I can and I will.

**Comment by gecube** [comment]
Made in 3e91c36986c8a326b9883a9af656e3c79d72d28d
Code is some kind of what we called "dirty" but it works :-)
