### ISSUE TITLE
Flooded clay pit

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#82]

**Comment by gecube** [comment]
What do you mean? Do you mean that fire can start in claypit, although it is near water? Or fires are impossible in claypit?

**Comment by dalerank** [comment]
In original game time to time claypit may be destroy by random action, forexample kindled by water... i set it here that don't forget about

**Comment by gecube** [comment]
You mean random event 0x48: "Flooded clay pit". You chose bad word and I didn't understand you.

**Comment by dalerank** [comment]
Fixed title )))
