### ISSUE TITLE
Instructions on building from git source.

### ISSUE THREAD

**Issue by Rovanion** [gecube/opencaesar3#88]
Hi,
I was unable to find the source code packages specified in the instructions. So instead I tried to build from the source code I just cloned from github since it would make it much easier to contribute back if I got the code up and running. Here is my walk this far:

``` bash
sudo apt-get install sudo apt-get install build-essential g++ libarchive-dev zlib1g-dev zlib1g unshield libsdl1.2* libsdl-image1.2* libsdl-mixer1.2* libboost1.50* libsdl-ttf2.0* qt4-dev-tools ctags libqxt-dev
```

Note the addition of libqxt-dev in order to be able to build sgreader.

``` bash
git clone git://github.com/gecube/opencaesar3.git
cd openceasar3/sgreader
cmake ./
make
sgreader
```

And then fallow the instructions for extracting the files from the installed original Caesar 3. After all that is done continue with:

``` bash
cd ..
cmake ./
make
./install.sh --pic-dir ~/caesar3_extract --data-dir ~/caesar3_orig
```

Now I believe it is here I encounter issues. Because the install script seems to report that it is done, but if I look closer I find:

``` bash
cp: cannot stat `../../../rov/Spel/Caesar3//Exe/*.map': No such file or directory
```

And no run.sh seems to have appeared in my source folder. Can you figure out what the issue is? 

Install.sh seems to copy a ton of data into the resources directory. And some of it is indeed loaded when I run ./caesar3. But it fails on ./resources/pics/pics_oc3.zip.

**Comment by dalerank** [comment]
you can download resource files from here https://github.com/gecube/opencaesar3/tree/master/resources... that i have't repeat all functions from original game, and need some my own pictures

**Comment by Rovanion** [comment]
Should these resources be used in addition to those from the CD or does the .7z contain all resources?

I was thinking I could help you a bit by getting the install instructions updated if needed be. Easier instructions means more people get to try the game and potentially contribute some code.

**Comment by Rovanion** [comment]
After extracting that archive into my resources folder the game now starts!

In order to answer the question whether the archive contained all the needed resources I cleared out the resources folder and tried once again just with the archive. Seems to work just fine.

Is it okay if I contribute an updated INSTALL_LINUX based on my findings here?

**Comment by gecube** [comment]
Hello!

Very glad to see.
You may write your own version of installation script. After that we will see how good it is.

**Comment by Rovanion** [comment]
So I've been testing out the new instructions and they seem to work well on fresh installs of Fedora 18, Ubuntu 12.04 LTS and Ubuntu 13.04. Take a look and let's see what you think of it:

(Link dead because old branch removed, see below comment)

**Comment by Rovanion** [comment]
Opened up pull request for the new INSTALL_LINUX: https://github.com/gecube/opencaesar3/pull/96
