### ISSUE TITLE
[Need implement] Granary infobox

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#92]
![6](https://f.cloud.github.com/assets/918081/571269/be66acde-c771-11e2-82a7-ef9f0b0a428a.png)

**Comment by ghost** [comment]
I've begun working on this and other info boxes and UI stuff. So far I have this, market and farm info boxes tidied up and with English localisation. Special orders isn't implemented at the moment, as far as I can tell the game logic doesn't support it yet either.

Granary info box screenshot:
![image](https://f.cloud.github.com/assets/4605795/606104/b4e0abb2-cd23-11e2-9fc8-f75b59a4206e.png)

**Comment by dalerank** [comment]
Fixed special orders button. No special orders window.
![oc3_ 2013_05_20_11_33_35](https://f.cloud.github.com/assets/918081/679813/20fc11b0-d97c-11e2-9ba3-4c2685b6be03.png)
