### ISSUE TITLE
[Need implement] Pause game when show infobox.

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#93]

**Comment by dalerank** [comment]
![21](https://f.cloud.github.com/assets/918081/584480/a2fc6c6a-c918-11e2-8b4b-30aeba2aac22.png)

**Comment by ghost** [comment]
I've been looking into this, and come up with a bit of a plan:
1. ScreenGame needs to be able to pause the game itself (player hits pause button) and let other parts of the code pause the game (info boxes, advisers, etc.). ScreenGame can be made pauseable by adding a boolean (init to false) and only running the city step if the boolean is false. Could allow other parts of code to pause game by using the signal/slot mechanism to toggle the boolean.
2. Info boxes would need to be wired up to send the appropriate signals when created and destroyed.
3. Pause key could be implemented in ScreenGame's event handler.

As far as I can see this shouldn't cause any problems with the simulation (from long timestep), but I haven't done any  testing yet. Everything except the sim step would still be run while paused.

**Comment by dalerank** [comment]
i see in original game, that paused only city life, but house/building animation are work. any ideas???
P.S. may be not call timeStep function for all??? `timeStep(time)` it main function in life cycle any objects in game

**Comment by gecube** [comment]
> but house/building animation are work. any ideas???

It is very important observation. 

> timeStep(time) it main function in life cycle any objects in game

Yes, I like it. The only thing to mention is not to break animation, because it can be binded to `timeStep` too. So we will need a small rewrite of code: to put gameplay and redrawing of screen and animation into different functions.
