### ISSUE TITLE
Models. config or hardcode???

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#94]
What way better, leave houses model in the file (see resource/house.model ) of a or move it in projects code, such as

class HouseModel
{
public:
  static const char\* model = "la-la-la";
}.

Any ideas???

**Comment by gecube** [comment]
I think such data must be placed into configuration files like resource/house.model
Also I want to remember you that original game was customizable, because it stores all values affecting building and house growth in separate plain text file.l

**Comment by dalerank** [comment]
ok... i think you right too))) thanks
