### ISSUE TITLE
Large pack file in .git makes up 98% of repo size.

### ISSUE THREAD

**Issue by Rovanion** [gecube/opencaesar3#95]
Hi,
While I'm building the guide I ended up cloning from git a couple of times and began wondering why it took such a long time. Turns out that there is a 96MB .pack-file called .git/objects/pack/pack-65741507f75e82cae801f52a3671ae04568f9c2d.pack .

A wild guess would be that this is some old, now removed, resources that git keeps as history. In itself it now makes up 98% of the entire repository.

I tried resolving it myself but the Stackoverflow answers seem to require some knowledge of where these files were so it should be relatively easy for you to resolve this issue: http://stackoverflow.com/questions/2164581/remove-file-from-git-repository-history

**Comment by dalerank** [comment]
i think gecube, as repo author, can remove some bigsize resource from repo... or have other way that resolve this

**Comment by gecube** [comment]
I removed huge resource files and rewrote commit history. Please take brief look. Now repo size is about 36MiB

**Comment by Rovanion** [comment]
As the files are compressed by git before download the downloaded data ended up being 25MB for me. Much better than before.

Perhaps it's possible to reduce it further but cutting it by 3/4: this is absolutely great!

**Comment by gecube** [comment]
P.S. now resources are available here: http://opencaesar3.org/files/resources.7z (supported by @hellium)
